travis:
  secure:
    BINSTAR_TOKEN: DFg71bCa+EJaFeMdjzQZc5W/V/HPpqMK4Few52wgdHLyBqPIjzOHb8j/jZ4VbkvtrOV+IXSLMBEAystruJ+dbgPXBbxTrGAH7PliZqkuDm4NmGcgCiO9mOK6cYLJ58tqSYlsm/HbtDj65LIrEh9SLJStGLO/d+xtRRJ4+ErlXrNFR5Y70QzimRkWkk7b/FuUifh3JDeN20H2mANqg0R/vq108BGxBvTE8ihXa5DRDRHI16JCyNTzVkNnCAQo3hdPUmSGygnLT1YBsFlBPUTsH4VyITj/JnfOu2lwktV+nufeDyw7IyAS7WUxS/5wxdQJURQyPe2ERWJLFbvBnJixDrHeON4yfQcnL0tfPo3wEsY0r8aulWWeDtxgkBO31ccVO05sNskwQUUeh5Rs7eC0o/CvXmvKmoKEoonHPA88oeLQT08Bzw/5UM5l7lgsEyln3YSlRAHLBCZRQpzZLTQLRRl4A+ivBuNO2KA90IxfNa3veu3fX7vHFP78Dl+jUTrq56evhbbNM22l50+nnHbtUEX/TXI38q/fXJ/gO5H7wfBNaAamkKZf0rrlG4izCPdE8dsb3wkeDXh8jDIPRKew0RMhjz8zWXtfTG14/zT7eI2CaITX0WDXff/rMSalQ3N6Yy7HoFesUDa9piUp+kmNZsvibm0IAb9s9Wg//CZALD4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
